### ISSUE TITLE
Time to get some meetings notes online!

### ISSUE THREAD

**Issue by lwasser** [pyopenscience/governance#1]
@choldgraf  @jlpalomino @mbjoseph @carsonfarmer  let's work together to get some meeting notes populated in this repo!

**Comment by choldgraf** [comment]
hey! I'll take a pass at putting stuff up soon! I've been away in DC at a conference but back this evening!

**Comment by choldgraf** [comment]
btw, I had dinner w/ @tracykteal while I was there, she says hello :-)

**Comment by jlpalomino** [comment]
@choldgraf FYI - I transferred the meeting notes from the google doc to hack.md, so you can use these files. You will see the links to the hack.md files in the same meeting notes google doc. Let me know if you have any trouble finding them. Thanks.

**Comment by lwasser** [comment]
Ahhhh @choldgraf  that warms my heart. i miss @tracykteal a lot and hope we end up on a project together again sometime soon!!

**Comment by lwasser** [comment]
@jlpalomino  why don't we create a meeting-notes dir here and add each hack.md file as an md file to that dir. we can have one for each time we meet like 2018-08-02-notes.md 

And each one should include who attended the meeting. @choldgraf i also have a pretty good GRA in mind for this. we shall see if it pans out!

**Comment by jlpalomino** [comment]
@lwasser OK will do.

**Comment by lwasser** [comment]
Thank you!!

**Comment by lwasser** [comment]
ok guys just a followup. @choldgraf liked to meeting notes on hackmd but there is a copy here. i think i like them here as they represent "a state in time" and are then under version control! ya?
